name: Deploy CDN

# Trigger the workflow on manual dispatch
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment: production

    steps:
    - name: R2 Upload
      uses: ryand56/r2-upload-action@latest
      with:
        r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
        r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
        r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        r2-bucket: ${{ secrets.R2_BUCKET }}
        source-dir: src
        destination-dir: ./
